### ISSUE TITLE
containerd-driver builds for arm

### ISSUE THREAD

**Issue by andruwa13** [Roblox/nomad-driver-containerd#61]
There are prebuilt binaries for amd

**Comment by shishir-a412ed** [comment]
@andruwa13 Are you asking about `containerd` or `nomad-driver-containerd`? Sorry, your question (or if it's a question or a statement 🙂 ) is not very clear.

**Comment by andruwa13** [comment]
nomad-driver-containerd

**Comment by shishir-a412ed** [comment]
@andruwa13 Thanks! There is no support for `arm` at present. But I can take a look.

**Comment by shishir-a412ed** [comment]
@andruwa13 I did some digging, and currently `containerd` is not **officially** supported on `arm64`

See [`Issue # 2901`](https://github.com/containerd/containerd/issues/2901) and [`Issue # 3664`](https://github.com/containerd/containerd/issues/3664). Since `containerd` depends on `cgo` (Linking against C libraries), the cross-compilation is a little bit non-trivial.

The good news 🙂 is, `containerd` has nightly builds for `arm64`. So you can download one from [`here`](https://github.com/containerd/containerd/actions?query=workflow%3ANightly) (Nightly --> Linux)

For `containerd-driver` Once we merge https://github.com/Roblox/nomad-driver-containerd/pull/67, you can compile `arm64` binary from the source by running 

```
$ make -f Makefile.arm64
```

I will also be releasing the `arm64` binaries from the next release, so one can just download from the release page and not have to compile it from the source.

**Comment by shishir-a412ed** [comment]
@andruwa13 I have also added the binary to the [`releases page`](https://github.com/Roblox/nomad-driver-containerd/releases/tag/v0.6) in case you want to download from there.
